from typing import Any, Dict, Optional, Self
from .code import SymbolCode
from .alias import Size, StrategyParams
from .base import LogLevel

class Config:
    def __init__(self, strategy: str, params: Dict[str, Any]): ...
    def fuxi_log_level(self, level: LogLevel) -> Self: ...
    def strategy_log_level(self, level: LogLevel) -> Self: ...
    def add_symbol(
        self, code: SymbolCode, taker: Optional[Size], maker: Optional[Size], lever: Optional[Size]
    ) -> Self: ...
