from typing import Optional
from .config import Config
from .alias import Size, Time

def millis_to_time(value: int) -> Time: ...
def nanos_to_time(value: int) -> Time: ...
def str_to_time(value: str) -> Time: ...
def time_to_str(value: Time, fmt: str) -> str: ...
def new_id() -> str: ...
def run_backtest(
    config: Config,
    begin: Time,
    end: Time,
    spot: Optional[Size],
    swap: Optional[Size],
    history_size: Optional[int],
): ...
