from typing import Dict, Optional
from .symbol import Symbol
from .code import SymbolCode
from .base import Volume
from .alias import StrategyParams, Time
from polars import DataFrame, Expr

class Fuxi:
    time: Time
    spot: Volume
    swap: Volume
    symbols: Dict[SymbolCode, Symbol]
    params: StrategyParams

    def trace(self, *args): ...
    def debug(self, *args): ...
    def info(self, *args): ...
    def warn(self, *args): ...
    def error(self, *args): ...
    def candles(self, code: SymbolCode, size: Optional[int]) -> DataFrame: ...
    def with_candles_column(self, code: SymbolCode, expr: Expr): ...
